version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
    networks:
      - symfony_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:delegated
      - ./var/cache:/var/www/html/var/cache:delegated
      - ./var/log:/var/www/html/var/log:delegated
      - ./vendor:/var/www/html/vendor:delegated
    environment:
      - OPCACHE_ENABLE=1
      - PHP_MEMORY_LIMIT=512M
      - PHP_PM_MAX_CHILDREN=50
      - PHP_PM_START_SERVERS=5
      - PHP_PM_MIN_SPARE_SERVERS=5
      - PHP_PM_MAX_SPARE_SERVERS=35
    depends_on:
      - database
      - redis
    networks:
      - symfony_network

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=2G --innodb_flush_log_at_trx_commit=2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:delegated
    networks:
      - symfony_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data: