controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\ProductController::index
api:
    path: /api
    controller: App\Controller\ProductController::index
    methods: GET

# JWT auth route
api_login_check:
    path: /api/login_check
